#!/bin/bash

files='wac rac'
states='ca il md ky'

for file in $files
do
  for state in $states
  do
    wget https://lehd.ces.census.gov/data/lodes/LODES7/${state}/${file}/${state}_${file}_S000_JT00_2015.csv.gz
    gunzip ~/${state}_${file}_S000_JT00_2015.csv.gz
  done
done

for state in $states
do
  wget https://lehd.ces.census.gov/data/lodes/LODES7/${state}/od/${state}_od_main_JT00_2015.csv.gz
  gunzip ~/${state}_od_main_JT00_2015.csv.gz
  wget https://lehd.ces.census.gov/data/lodes/LODES7/${state}/${state}_xwalk.csv.gz
  gunzip ~/${state}_xwalk.csv.gz
done